CREATE PROCEDURE USP_LISTARCONTACTOS
AS
BEGIN
SELECT * FROM CONTACTO
END

EXECUTE USP_LISTARCONTACTOS


CREATE PROCEDURE USP_BUSCARCONTACTO
@CEDULA VARCHAR(20)
AS
BEGIN
SELECT * FROM CONTACTO WHERE @CEDULA=CEDULA
END

EXECUTE USP_BUSCARCONTACTO 'CC1'