//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppConsumir.operaciones {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebService1Soap", Namespace="http://tempuri.org/")]
    public partial class WebService1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback sumaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CircunferenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrianguloEqOperationCompleted;
        
        private System.Threading.SendOrPostCallback RectanguloOperationCompleted;
        
        private System.Threading.SendOrPostCallback CilindroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService1() {
            this.Url = global::AppConsumir.Properties.Settings.Default.AppConsumir_operaciones_WebService1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RestaCompletedEventHandler RestaCompleted;
        
        /// <remarks/>
        public event sumaCompletedEventHandler sumaCompleted;
        
        /// <remarks/>
        public event CircunferenciaCompletedEventHandler CircunferenciaCompleted;
        
        /// <remarks/>
        public event TrianguloEqCompletedEventHandler TrianguloEqCompleted;
        
        /// <remarks/>
        public event RectanguloCompletedEventHandler RectanguloCompleted;
        
        /// <remarks/>
        public event CilindroCompletedEventHandler CilindroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Resta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Resta(double numeroUno, double numeroDos) {
            object[] results = this.Invoke("Resta", new object[] {
                        numeroUno,
                        numeroDos});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void RestaAsync(double numeroUno, double numeroDos) {
            this.RestaAsync(numeroUno, numeroDos, null);
        }
        
        /// <remarks/>
        public void RestaAsync(double numeroUno, double numeroDos, object userState) {
            if ((this.RestaOperationCompleted == null)) {
                this.RestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestaOperationCompleted);
            }
            this.InvokeAsync("Resta", new object[] {
                        numeroUno,
                        numeroDos}, this.RestaOperationCompleted, userState);
        }
        
        private void OnRestaOperationCompleted(object arg) {
            if ((this.RestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestaCompleted(this, new RestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/suma", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double suma(double numeroUno, double numeroDos) {
            object[] results = this.Invoke("suma", new object[] {
                        numeroUno,
                        numeroDos});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void sumaAsync(double numeroUno, double numeroDos) {
            this.sumaAsync(numeroUno, numeroDos, null);
        }
        
        /// <remarks/>
        public void sumaAsync(double numeroUno, double numeroDos, object userState) {
            if ((this.sumaOperationCompleted == null)) {
                this.sumaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsumaOperationCompleted);
            }
            this.InvokeAsync("suma", new object[] {
                        numeroUno,
                        numeroDos}, this.sumaOperationCompleted, userState);
        }
        
        private void OnsumaOperationCompleted(object arg) {
            if ((this.sumaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sumaCompleted(this, new sumaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Circunferencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Circunferencia(double radio) {
            object[] results = this.Invoke("Circunferencia", new object[] {
                        radio});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CircunferenciaAsync(double radio) {
            this.CircunferenciaAsync(radio, null);
        }
        
        /// <remarks/>
        public void CircunferenciaAsync(double radio, object userState) {
            if ((this.CircunferenciaOperationCompleted == null)) {
                this.CircunferenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCircunferenciaOperationCompleted);
            }
            this.InvokeAsync("Circunferencia", new object[] {
                        radio}, this.CircunferenciaOperationCompleted, userState);
        }
        
        private void OnCircunferenciaOperationCompleted(object arg) {
            if ((this.CircunferenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CircunferenciaCompleted(this, new CircunferenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrianguloEq", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double TrianguloEq(double lado) {
            object[] results = this.Invoke("TrianguloEq", new object[] {
                        lado});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void TrianguloEqAsync(double lado) {
            this.TrianguloEqAsync(lado, null);
        }
        
        /// <remarks/>
        public void TrianguloEqAsync(double lado, object userState) {
            if ((this.TrianguloEqOperationCompleted == null)) {
                this.TrianguloEqOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrianguloEqOperationCompleted);
            }
            this.InvokeAsync("TrianguloEq", new object[] {
                        lado}, this.TrianguloEqOperationCompleted, userState);
        }
        
        private void OnTrianguloEqOperationCompleted(object arg) {
            if ((this.TrianguloEqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrianguloEqCompleted(this, new TrianguloEqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Rectangulo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Rectangulo(double altura, double baseL) {
            object[] results = this.Invoke("Rectangulo", new object[] {
                        altura,
                        baseL});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void RectanguloAsync(double altura, double baseL) {
            this.RectanguloAsync(altura, baseL, null);
        }
        
        /// <remarks/>
        public void RectanguloAsync(double altura, double baseL, object userState) {
            if ((this.RectanguloOperationCompleted == null)) {
                this.RectanguloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRectanguloOperationCompleted);
            }
            this.InvokeAsync("Rectangulo", new object[] {
                        altura,
                        baseL}, this.RectanguloOperationCompleted, userState);
        }
        
        private void OnRectanguloOperationCompleted(object arg) {
            if ((this.RectanguloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RectanguloCompleted(this, new RectanguloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Cilindro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Cilindro(double radio, double altura) {
            object[] results = this.Invoke("Cilindro", new object[] {
                        radio,
                        altura});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void CilindroAsync(double radio, double altura) {
            this.CilindroAsync(radio, altura, null);
        }
        
        /// <remarks/>
        public void CilindroAsync(double radio, double altura, object userState) {
            if ((this.CilindroOperationCompleted == null)) {
                this.CilindroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCilindroOperationCompleted);
            }
            this.InvokeAsync("Cilindro", new object[] {
                        radio,
                        altura}, this.CilindroOperationCompleted, userState);
        }
        
        private void OnCilindroOperationCompleted(object arg) {
            if ((this.CilindroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CilindroCompleted(this, new CilindroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RestaCompletedEventHandler(object sender, RestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void sumaCompletedEventHandler(object sender, sumaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sumaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sumaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CircunferenciaCompletedEventHandler(object sender, CircunferenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CircunferenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CircunferenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void TrianguloEqCompletedEventHandler(object sender, TrianguloEqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrianguloEqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrianguloEqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void RectanguloCompletedEventHandler(object sender, RectanguloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RectanguloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RectanguloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CilindroCompletedEventHandler(object sender, CilindroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CilindroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CilindroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591